//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultant()
        {
            this.ProjectRoles = new HashSet<ProjectRole>();
        }
    
        public int consultantId { get; set; }
        public string consultantName { get; set; }
        public Nullable<System.DateTime> sogetiStartDate { get; set; }
        public bool activeEmployee { get; set; }
        public string lastEditedBy { get; set; }
        public System.DateTime editDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectRole> ProjectRoles { get; set; }
    }
}
