//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostOpportunity
    {
        public int projectId { get; set; }
        public int lostReasonId { get; set; }
        public string lastEditedBy { get; set; }
        public System.DateTime editDate { get; set; }
    
        public virtual LostReason LostReason { get; set; }
        public virtual Project Project { get; set; }
    }
}
