//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.LostOpportunities = new HashSet<LostOpportunity>();
        }
    
        public int projectId { get; set; }
        public int clientId { get; set; }
        public int projectStatusID { get; set; }
        public string location { get; set; }
        public string sponsor { get; set; }
        public System.DateTime requestDate { get; set; }
        public string projectName { get; set; }
        public bool projectActive { get; set; }
        public string comment { get; set; }
        public string lastEditedBy { get; set; }
        public System.DateTime editDate { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LostOpportunity> LostOpportunities { get; set; }
        public virtual ProjectStatus ProjectStatus { get; set; }
        public virtual ProjectRole ProjectRole { get; set; }
    }
}
