//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRole
    {
        public int projectRoleId { get; set; }
        public int projectId { get; set; }
        public Nullable<int> consultantId { get; set; }
        public string projectRoleName { get; set; }
        public string maxTargetGrade { get; set; }
        public string targetedNewHireGrade { get; set; }
        public Nullable<bool> candidateConfirmed { get; set; }
        public Nullable<System.DateTime> expectedStartDate { get; set; }
        public Nullable<System.DateTime> actualStartDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string lastEditedBy { get; set; }
        public System.DateTime editDate { get; set; }
    
        public virtual Consultant Consultant { get; set; }
        public virtual Project Project { get; set; }
    }
}
